name: PR Build

on:
 workflow_dispatch:
 pull_request:

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    outputs:
      version: ${{ steps.package-version.outputs.version }}

    steps:
      - id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%s')"

      - name: Restore the previous run result
        uses: actions/cache@v2
        with:
          path: |
            run_result
          key: ${{ github.run_id }}-${{ github.sha }}-${{ matrix.os }}-${{ steps.timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ github.run_id }}-${{ github.sha }}-${{ matrix.os }}-

      - id: result
        run: echo "::set-output name=status::$(test -f run_result && cat run_result || echo 'first-time')"
        shell: bash

      - name: Check out Git repository
        if: ${{ steps.result.outputs.status != 'success' }}
        uses: actions/checkout@v2

      - name: Install Node.js, NPM
        if: ${{ steps.result.outputs.status != 'success' }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Get yarn cache directory path
        if: ${{ steps.result.outputs.status != 'success' }}
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        if: ${{ steps.result.outputs.status != 'success' }}
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install
        if: ${{ steps.result.outputs.status != 'success' }}
        run: |
          yarn install --prefer-offline

      - name: yarn lint and build
        if: ${{ steps.result.outputs.status != 'success' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn lint
          yarn postinstall

      # Download go-spacemesh
      - name: Get specified Go-spacemesh version
        id: latestNode
        run: echo "::set-output name=version::$(cat ./node/use-version)"
      
      - id: cache-gospacemesh
        uses: actions/cache@v2
        with:
          path: |
            ./node/*
            !./node/use-version
          key: ${{ matrix.os }}-${{ hashFiles('./node/use-version') }}
          restore-keys: ${{ matrix.os }}-${{ hashFiles('./node/use-version') }}
        
      - name: Prepare link to go-spacemesh binary
        if: steps.cache-gospacemesh.outputs.cache-hit != 'true'
        id: node-link
        run: |
          echo "::set-output name=link::https://storage.googleapis.com/go-spacemesh-release-builds/${{ steps.latestNode.outputs.version }}/${{matrix.os}}/go-spacemesh${{matrix.os == 'windows-latest' && '.exe' || ''}}"
      
      - name: Check for go-spacemesh artifact existence
        if: steps.cache-gospacemesh.outputs.cache-hit != 'true'
        run: |
          [[ $(curl -I -L -w "%{http_code}" -o ${{ matrix.os == 'windows-latest' && 'NUL' || '/dev/null'}} ${{steps.node-link.outputs.link}}) == "200" ]] &&
          echo "Atifacts found: ${{steps.node-link.outputs.link}}" && exit 0 ||
          echo "Not found: ${{steps.node-link.outputs.link}}" && exit 1
        shell: bash

      - id: platform
        if: steps.cache-gospacemesh.outputs.cache-hit != 'true'
        run: |
          echo "::set-output name=dir::${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'mac' || 'linux'}}"
          echo "::set-output name=ext::${{ matrix.os == 'windows-latest' && '.exe' || ''}}"

      - name: Download Go-Spacemesh
        if: steps.cache-gospacemesh.outputs.cache-hit != 'true'
        run: |
          curl -L --output ./node/${{ steps.platform.outputs.dir }}/go-spacemesh${{ steps.platform.outputs.ext}} --create-dirs ${{steps.node-link.outputs.link}}

      - name: Set CHMOD on Go-Spacemesh
        if: matrix.os != 'windows-latest'
        run: (cd ./node/${{ steps.platform.outputs.dir }}; chmod -R +x * .)
      
      # Build
      - name: yarn build
        run: yarn build

      # Create binaries
      - if: matrix.os == 'ubuntu-latest'
        name: Build linux app
        run: yarn package-linux
      - if: matrix.os == 'windows-latest'
        name: Build windows app
        run: yarn package-win
      - if: matrix.os == 'macos-latest'
        name: Build mac app
        run: yarn package-mac
        env:
          DONT_SIGN_APP: true # Do not sign the development artifacts

      # Upload artifacts to GCS
      - name: get-smapp-version
        id: package-version
        uses: tyankatsu0105/read-package-version-actions@v1

      - name: Set up GCloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - if: matrix.os == 'macos-latest'
        name: upload macos build
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./release/Spacemesh-${{ steps.package-version.outputs.version }}.dmg
          destination: ${{ secrets.GCP_BUCKET }}/pr-${{ github.sha }}

      - if: matrix.os == 'windows-latest'
        name: upload windows build
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./release/Spacemesh Setup ${{ steps.package-version.outputs.version }}.exe
          destination: ${{ secrets.GCP_BUCKET }}/pr-${{ github.sha }}
      
      - if: matrix.os == 'ubuntu-latest'
        name: upload linux build
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./release/spacemesh_app_${{ steps.package-version.outputs.version }}_amd64.deb
          destination: ${{ secrets.GCP_BUCKET }}/pr-${{ github.sha }}

      # Save the run result on success and it should be cached
      - run: echo "success" > run_result
        if: ${{ steps.result.outputs.status != 'success' }}
  
  post-links:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Links to artifacts
        run: |
          echo "Windows: https://storage.googleapis.com/smapp/pr-${{ github.sha }}/Spacemesh%20Setup%20${{ needs.build-and-upload.outputs.version }}.exe"
          echo "https://storage.googleapis.com/smapp/pr-${{ github.sha }}/spacemesh_app_${{ needs.build-and-upload.outputs.version }}_amd64.deb"
          echo "https://storage.googleapis.com/smapp/pr-${{ github.sha }}/Spacemesh-${{ needs.build-and-upload.outputs.version }}.dmg"
      - name: Post links to PR
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ## Compiled Binaries
            - Windows: https://storage.googleapis.com/smapp/pr-${{ github.sha }}/Spacemesh%20Setup%20${{ needs.build-and-upload.outputs.version }}.exe
            - Linux: https://storage.googleapis.com/smapp/pr-${{ github.sha }}/spacemesh_app_${{ needs.build-and-upload.outputs.version }}_amd64.deb
            - Mac: https://storage.googleapis.com/smapp/pr-${{ github.sha }}/Spacemesh-${{ needs.build-and-upload.outputs.version }}.dmg